src/Entity/Rapport.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RapportRepository")
 */
class Rapport
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $file;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;


    /**
     * @ORM\ManyToOne(targetEntity="Enseignant", inversedBy="rapports")
     */
    private $enseignants;

    /**
     * @ORM\ManyToOne(targetEntity="Etudiant", inversedBy="rapports")
    */
    private $etudiants;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $classe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $section;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $annee;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre()
    {
        return $this->titre;
    }
    public function setTitre($titre)
    {
        $this->titre = $titre;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEnseignants()
    {
        return $this->enseignants;
    }
    public function setEnseignants($enseignants)
    {
        $this->enseignants = $enseignants;
    }

    public function getClasse()
    {
        return $this->classe;
    }
    public function setClasse($classe): void
    {
        $this->classe = $classe;
    }

    public function getSection(): ?string
    {
        return $this->section;
    }
    public function setSection(string $section): self
    {
        $this->section = $section;

        return $this;
    }

    public function getAnnee()
    {
        return $this->annee;
    }
    public function setAnnee($annee): void
    {
        $this->annee = $annee;
    }

    /**
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param string $file
     */
    public function setFile($file): void
    {
        $this->file = $file;
    }

    public function getFilePath()
    {
        return "/uploads/{$this->file}";
    }
}

src/Form/RapportType.php
<?php

namespace App\Form;

use App\Entity\Enseignant;
use App\Entity\Rapport;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RapportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre',TextType::class, ['attr' => ['class' =>'form-control']])
            ->add('file', FileType::class, array( 'data_class' => null,'required' => false, 'attr' => ['class' =>'form-control']))
            ->add('description', TextareaType::class, ['attr' => ['class' =>'form-control']])
            ->add('enseignants', EntityType::class, [
                'class' => Enseignant::class,
                'choice_label' => 'mail',
                'attr' => ['class' =>'form-control']])
//            ->add('etudiants')
            ->add('classe', ChoiceType::class, ['choices'  => [ ''=> null,'3 éme' => true, '4 éme' => true, '5 éme' => true ], 'attr' => ['class' =>'form-control']])
            ->add('section', ChoiceType::class, ['choices'  => [ ''=> null, 'Licence' => true, 'Cycle ingéniere' => true, 'Management' => true], 'attr' => ['class' =>'form-control']])
            ->add('annee', NumberType::class, ['attr' => ['class' =>'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => Rapport::class,]);
    }
}

src/Controller/RapportController.php
<?php

namespace App\Controller;

use App\Entity\Rapport;
use App\Form\RapportType;
use App\Repository\RapportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * @Route("/rapport")
 */
class RapportController extends AbstractController
{
    /**
     * @Route("/", name="rapport_index", methods={"GET"})
     */
    public function index(RapportRepository $rapportRepository): Response
    {
        return $this->render('rapport/index.html.twig', ['rapports' => $rapportRepository->findAll(),]);
    }

    /**
     * @Route("/home", name="rapport_home", methods={"GET"})
     */
    public function home(RapportRepository $rapportRepository): Response
    {
        return $this->render('rapport/home.html.twig', ['rapports' => $rapportRepository->findAll(),]);
    }

    /**
     * @Route("/new", name="rapport_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $rapport = new Rapport();
        $form = $this->createForm(RapportType::class, $rapport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $rapport->getFile();
            $fileName = md5(uniqid()).'.'.$file->guessExtension();
            $file->move(
                $this->getParameter('upload_directory'),$fileName);
            $rapport->setFile($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($rapport);
            $em->flush();

            return $this->redirectToRoute('rapport_index');
        }

        return $this->render('rapport/new.html.twig', [
            'rapport' => $rapport,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rapport_show", methods={"GET"})
     */
    public function show(Rapport $rapport): Response
    {
        return $this->render('rapport/show.html.twig', ['rapport' => $rapport,]);
    }

    /**
     * @Route("/{id}/edit", name="rapport_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Rapport $rapport): Response
    {
        $form = $this->createForm(RapportType::class, $rapport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rapport_index');
        }

        return $this->render('rapport/edit.html.twig', [
            'rapport' => $rapport,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rapport_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Rapport $rapport): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rapport->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rapport);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rapport_index');
    }


}

templates/rapport/_form.html.twig
{% block body %}

    <style>
        .example-wrapper { margin: auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #d2959b; padding: 2px 6px; }
    </style>

    {{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="form">
        <div class="form-group"> {{ form_row(form.titre) }} </div>
        <div class="form-group"> {{ form_row(form.file) }} </div>
        <div class="form-group"> {{ form_row(form.description) }} </div>
        <div class="form-group"> {{ form_row(form.annee) }} </div>
        <div class="form-group"> {{ form_row(form.classe) }} </div>
        <div class="form-group"> {{ form_row(form.section) }} </div>
        <div class="form-group"> {{ form_row(form.enseignants) }} </div>
        <div class="col" id="some-custom-id">
            <button class="btn btn-default " style="background: #d2959b">{{ button_label|default('Ajouter rapport') }}</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/rapport/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Rapport{% endblock %}

{% block body %}
    <h1>Modifier Rapport</h1>

    {{ include('rapport/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('rapport_index') }}" class="btn btn-default " style="background: #d2959b">return à la liste</a>

    {{ include('rapport/_delete_form.html.twig') }}
{% endblock %}

templates/rapport/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        thead {color:indianred;}
        tbody {color:black;}
        tfoot {color:red;}
    </style>

    <div class="wrapper">
        <div class="dashboard-headline">

            <div class="example-wrapper col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading center">
                        Rapport PDS
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('rapport_new') }}">Ajout Rapport PDS</a>
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('rapport_index') }}">Liste Rapport PDS</a>
                    </div>
                </div>
            </div>

            <div class="example-wrapper col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading center">
                        Rapport PPE
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('rapport_new') }}">Ajout Rapport PPE</a>
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('rapport_index') }}">Liste Rapport PPE</a>
                    </div>
                </div>
            </div>

            <div class="example-wrapper col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading center">
                        Rapport PFE
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('rapport_new') }}">Ajout Rapport PFE</a>
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('rapport_index') }}">Liste Rapport PFE</a>
                    </div>
                </div>
            </div>

            <div class="example-wrapper col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading center">
                        Document
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('admin_document') }}">Voir les document </a>
                    </div>
                </div>
            </div>

            <div class="example-wrapper col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading center">
                        Document
                    </div>
                    <div class="panel-body">
                        <a  href="{{ path('soutenance_date') }}">Voir les date de soutenances </a>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/rapport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rapport index{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 1100px; width: 200%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    thead {color:indianred;}
    tbody {color:black;}
    tfoot {color:red;}
</style>

<div class="example-wrapper">

   <table class="table"  >
        <thead>
            <tr>
                <th><div class="form-check" >Titre</div></th>
                <th><div class="form-check">Description</div></th>
                <th><div class="form-check"></div></th>
                <th><div class="form-check"></div></th>
            </tr>
        </thead>
        <tbody>
        {% for rapport in rapports %}
            <tr>
                <td><div class="form-check"> {{ rapport.titre }}</div></td>
                <td><div class="form-check"> {{ rapport.description }}</div></td>
                <td><div class="form-check"> <a href="{{ absolute_url(rapport.filePath)}}" class="fa fa-download" download></a> </div></td>
                <td><div class="form-check">
                    <a href="{{ path('rapport_show', {'id': rapport.id}) }}" class="glyphicon glyphicon-list"></a>
                    <a href="{{ path('rapport_edit', {'id': rapport.id}) }}" class="glyphicon glyphicon-edit"></a>
                    <a>{{ include('rapport/_delete_form.html.twig') }}    </a>   </div>         </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5"> Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

    <a href="{{ path('rapport_new') }}" class="btn btn-default " style="background: #d2959b">Ajouter un rapport</a>

{% endblock %}

templates/rapport/list.html.twig
{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 1100px; width: 200%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        thead {color:indianred;}
        tbody {color:black;}
        tfoot {color:red;}
    </style>

    <h1>Rapport</h1>

    <div class="example-wrapper">

        <table class="table"  >
            <thead>
            <tr>
                <th><div class="form-check" >Titre</div></th>
                <th><div class="form-check">Description</div></th>

            </tr>
            </thead>
            <tbody>
            {% for rapport in rapport %}
                <tr>
                    <td><div class="form-check"> {{ rapport.titre }}</div></td>
                    <td><div class="form-check"> {{ rapport.description }}</div></td>

                </tr>

            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

templates/rapport/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Rapport{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 0em auto; max-width: 1200px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #d2959b; padding: 1px 2px; }
    </style>
    <h1>Ajouter votre Rapport</h1>

<div class="example-wrapper">

    {{ include('rapport/_form.html.twig') }}

    <a href="{{ path('rapport_index') }}" class="btn btn-default" style="background: cadetblue">Voir la list</a>
</div>

{% endblock %}

templates/rapport/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rapport{% endblock %}

{% block body %}

    <style>
        .example-wrapper { margin: auto; max-width: 500px; width: 10%; font: 20px/1.5 sans-serif; }
        .example-wrapper code { background: #d2959b; padding: 2px 6px; }
    </style>
    <h1>Rapport</h1>

<div class="form wrapper">
    <table class="table">
        <tbody>

            <tr>
                <div class="form-group"> <th>Titre</th></div>
                <div class="form-group"><td>{{ rapport.titre }}</td></div>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ rapport.description }}</td>
            </tr>

        </tbody>
    </table>
</div>


    <a href="{{ path('rapport_index') }}" class="btn btn-default glyphicon glyphicon-list" style="background: #5eb5e0"></a>
    <a href="{{ path('rapport_edit', {'id': rapport.id}) }}"  class="btn btn-default glyphicon glyphicon-edit" style="background: #5eb5e0"></a>
    <a>{{ include('rapport/_delete_form.html.twig') }}</a>
{% endblock %}